"""initial schema

Revision ID: 000000000001
Revises:
Create Date: 2026-08-21 14:37:44.028597

Single consolidated schema (the project keeps one squashed initial migration).
Re-squashed from the previous chain (000000000001..dab99b6a8b21) by regenerating
from the models via ``alembic revision --autogenerate``, so it carries the
metadata naming convention, composite/hot-path indexes, CHECK constraints,
explicit ON DELETE rules (SET NULL for audit/actor FKs, CASCADE for
order/preorder children), DB-level server defaults, and every column added
since the previous squash (branch printing switches, preorder ``variant``,
product ``external_code``). ``users`` and ``branches`` form a mutual FK cycle,
broken here by creating ``users`` without the ``branch_id`` FK and adding it
back afterwards. A database on an older revision is recreated (this project
drops and rebuilds prod rather than chaining onto the old history).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000000000001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # users <-> branches form a circular FK (users.branch_id -> branches.id;
    # branches.created_by/updated_by -> users.id). Autogenerate can't order a
    # mutual cycle, so create users first WITHOUT the branch_id FK, then branches,
    # then add the branch_id FK back.
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_users_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_users_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_branch_id'), 'users', ['branch_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('print_labels_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('print_consolidated_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_branches_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_branches_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_branches'))
    )
    op.create_index(op.f('ix_branches_code'), 'branches', ['code'], unique=True)
    op.create_foreign_key(op.f('fk_users_branch_id_branches'), 'users', 'branches', ['branch_id'], ['id'])
    op.create_table('additional_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('price >= 0', name=op.f('ck_additional_services_price_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_additional_services_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_additional_services_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_additional_services')),
    sa.UniqueConstraint('name', name=op.f('uq_additional_services_name'))
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_clients_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_clients_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients')),
    sa.UniqueConstraint('identifier', name=op.f('uq_clients_identifier'))
    )
    op.create_table('print_agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_print_agents_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_print_agents_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_print_agents_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_print_agents')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_print_agents_token_hash'))
    )
    op.create_index(op.f('ix_print_agents_branch_id'), 'print_agents', ['branch_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('external_code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('price >= 0', name=op.f('ck_products_price_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_products_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_products_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('code', name=op.f('uq_products_code')),
    sa.UniqueConstraint('external_code', name=op.f('uq_products_external_code')),
    sa.UniqueConstraint('name', name=op.f('uq_products_name'))
    )
    op.create_index(op.f('ix_products_type'), 'products', ['type'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_refresh_tokens_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_refresh_tokens_updated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kerf', sa.Float(), nullable=False),
    sa.Column('top_trim', sa.Float(), nullable=False),
    sa.Column('bottom_trim', sa.Float(), nullable=False),
    sa.Column('left_trim', sa.Float(), nullable=False),
    sa.Column('right_trim', sa.Float(), nullable=False),
    sa.Column('edge_banding_waste_factor', sa.Float(), nullable=False),
    sa.Column('half_board_markup_pct', sa.Float(), nullable=False),
    sa.Column('preorder_validity_days', sa.Integer(), nullable=False),
    sa.Column('max_open_preorders_per_client', sa.Integer(), nullable=False),
    sa.Column('price_tiers', sa.JSON(), nullable=False),
    sa.Column('company_name', sa.String(length=128), nullable=False),
    sa.Column('company_tagline', sa.String(length=256), nullable=False),
    sa.Column('company_email', sa.String(length=128), nullable=False),
    sa.Column('company_phone', sa.String(length=128), nullable=False),
    sa.Column('company_branches', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('id = 1', name=op.f('ck_settings_singleton')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_settings_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_settings_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings'))
    )
    op.create_table('user_login_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_login_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_login_events'))
    )
    op.create_index('ix_user_login_events_user_created', 'user_login_events', ['user_id', 'created_at'], unique=False)
    op.create_table('optimization_drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_optimization_drafts_branch_id_branches')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_optimization_drafts_client_id_clients')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_optimization_drafts_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_optimization_drafts_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_drafts'))
    )
    op.create_index(op.f('ix_optimization_drafts_branch_id'), 'optimization_drafts', ['branch_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('optimization_snapshot', sa.JSON(), nullable=False),
    sa.Column('optimization_hash', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('price_tier_code', sa.String(length=32), server_default='consumidor', nullable=False),
    sa.Column('discount_rate', sa.Float(), server_default='0', nullable=False),
    sa.Column('discount_amount', sa.Float(), server_default='0', nullable=False),
    sa.Column('additional_services_total', sa.Float(), server_default='0', nullable=False),
    sa.Column('total_boards_used', sa.Integer(), nullable=False),
    sa.Column('external_invoice_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_to_label', sa.String(length=128), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('dispatched_by', sa.Integer(), nullable=True),
    sa.Column('dispatched_by_label', sa.String(length=128), nullable=True),
    sa.Column('payment_cash_amount', sa.Float(), nullable=True),
    sa.Column('payment_credit_amount', sa.Float(), nullable=True),
    sa.Column('banding_status', sa.String(length=16), server_default='not_applicable', nullable=False),
    sa.Column('banding_started_at', sa.DateTime(), nullable=True),
    sa.Column('banding_started_by', sa.Integer(), nullable=True),
    sa.Column('banding_started_by_label', sa.String(length=128), nullable=True),
    sa.Column('banding_finished_at', sa.DateTime(), nullable=True),
    sa.Column('banding_finished_by', sa.Integer(), nullable=True),
    sa.Column('banding_finished_by_label', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('additional_services_total >= 0', name=op.f('ck_orders_additional_services_total_non_negative')),
    sa.CheckConstraint('discount_amount >= 0', name=op.f('ck_orders_discount_amount_non_negative')),
    sa.CheckConstraint('discount_rate >= 0 AND discount_rate <= 1', name=op.f('ck_orders_discount_rate_ratio')),
    sa.CheckConstraint('payment_cash_amount >= 0', name=op.f('ck_orders_payment_cash_non_negative')),
    sa.CheckConstraint('payment_credit_amount >= 0', name=op.f('ck_orders_payment_credit_non_negative')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_orders_subtotal_non_negative')),
    sa.CheckConstraint('total >= 0', name=op.f('ck_orders_total_non_negative')),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_orders_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['banding_finished_by'], ['users.id'], name=op.f('fk_orders_banding_finished_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['banding_started_by'], ['users.id'], name=op.f('fk_orders_banding_started_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_orders_branch_id_branches')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_orders_client_id_clients')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_orders_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dispatched_by'], ['users.id'], name=op.f('fk_orders_dispatched_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_orders_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('code', name=op.f('uq_orders_code'))
    )
    op.create_index('ix_orders_branch_status', 'orders', ['branch_id', 'status'], unique=False)
    op.create_index('ix_orders_client_id', 'orders', ['client_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('body', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_notifications_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_order_id'), 'notifications', ['order_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('order_attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_key', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_order_attachments_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_attachments_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_order_attachments_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_attachments')),
    sa.UniqueConstraint('stored_key', name=op.f('uq_order_attachments_stored_key'))
    )
    op.create_index(op.f('ix_order_attachments_order_id'), 'order_attachments', ['order_id'], unique=False)
    op.create_table('order_boards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('sheet_number', sa.Integer(), nullable=False),
    sa.Column('material_key', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_code', sa.String(length=64), nullable=True),
    sa.Column('product_name', sa.String(length=128), nullable=True),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('thickness', sa.Float(), nullable=False),
    sa.Column('half_board', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('remainders', sa.JSON(), nullable=True),
    sa.Column('cuts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_order_boards_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_boards_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_boards_product_id_products')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_order_boards_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_boards'))
    )
    op.create_index(op.f('ix_order_boards_order_id'), 'order_boards', ['order_id'], unique=False)
    op.create_table('order_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_code', sa.String(length=32), nullable=True),
    sa.Column('product_name', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price_snapshot', sa.Float(), nullable=False),
    sa.Column('line_total', sa.Float(), nullable=False),
    sa.Column('avg_efficiency', sa.Float(), nullable=True),
    sa.Column('total_area_m2', sa.Float(), nullable=True),
    sa.Column('linear_m', sa.Float(), nullable=True),
    sa.Column('half_board', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('line_total >= 0', name=op.f('ck_order_lines_line_total_non_negative')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_lines_quantity_positive')),
    sa.CheckConstraint('unit_price_snapshot >= 0', name=op.f('ck_order_lines_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_order_lines_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_lines_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_lines_product_id_products')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_order_lines_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_lines'))
    )
    op.create_index('ix_order_lines_order_id', 'order_lines', ['order_id'], unique=False)
    op.create_table('order_pieces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('can_rotate', sa.Boolean(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_pieces_quantity_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_order_pieces_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_pieces_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_pieces_product_id_products')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_order_pieces_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_pieces'))
    )
    op.create_index('ix_order_pieces_order_id', 'order_pieces', ['order_id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=128), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_order_status_history_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_order_status_history_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_status_history_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_order_status_history_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_status_history'))
    )
    op.create_index('ix_order_status_history_order_id', 'order_status_history', ['order_id'], unique=False)
    op.create_table('preorders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('materials', sa.JSON(), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('additional_services', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('price_tier_code', sa.String(length=32), server_default='consumidor', nullable=False),
    sa.Column('strategy', sa.String(length=32), server_default='default', nullable=False),
    sa.Column('variant', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('client_note', sa.String(length=512), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_preorders_branch_id_branches')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_preorders_client_id_clients')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_preorders_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_preorders_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_preorders_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preorders')),
    sa.UniqueConstraint('code', name=op.f('uq_preorders_code'))
    )
    op.create_index('ix_preorders_branch_status', 'preorders', ['branch_id', 'status'], unique=False)
    op.create_index('ix_preorders_client_status', 'preorders', ['client_id', 'status'], unique=False)
    op.create_table('order_placed_pieces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.String(length=160), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('original_width', sa.Float(), nullable=False),
    sa.Column('original_height', sa.Float(), nullable=False),
    sa.Column('rotated', sa.Boolean(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=True),
    sa.Column('cut_at', sa.DateTime(), nullable=True),
    sa.Column('cut_by', sa.Integer(), nullable=True),
    sa.Column('cut_by_label', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['order_boards.id'], name=op.f('fk_order_placed_pieces_board_id_order_boards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_order_placed_pieces_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cut_by'], ['users.id'], name=op.f('fk_order_placed_pieces_cut_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_placed_pieces_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_order_placed_pieces_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_placed_pieces'))
    )
    op.create_index(op.f('ix_order_placed_pieces_board_id'), 'order_placed_pieces', ['board_id'], unique=False)
    op.create_index(op.f('ix_order_placed_pieces_order_id'), 'order_placed_pieces', ['order_id'], unique=False)
    op.create_table('preorder_review_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('preorder_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('used_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_preorder_review_links_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preorder_id'], ['preorders.id'], name=op.f('fk_preorder_review_links_preorder_id_preorders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_preorder_review_links_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preorder_review_links')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_preorder_review_links_token_hash'))
    )
    op.create_index(op.f('ix_preorder_review_links_preorder_id'), 'preorder_review_links', ['preorder_id'], unique=False)
    op.create_table('preorder_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('preorder_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=128), nullable=True),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_preorder_status_history_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_preorder_status_history_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preorder_id'], ['preorders.id'], name=op.f('fk_preorder_status_history_preorder_id_preorders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_preorder_status_history_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preorder_status_history'))
    )
    op.create_index(op.f('ix_preorder_status_history_preorder_id'), 'preorder_status_history', ['preorder_id'], unique=False)
    op.create_table('print_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('placed_piece_id', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=16), nullable=False),
    sa.Column('payload_format', sa.String(length=8), nullable=False),
    sa.Column('payload_path', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['print_agents.id'], name=op.f('fk_print_jobs_agent_id_print_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_print_jobs_branch_id_branches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_print_jobs_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_print_jobs_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['placed_piece_id'], ['order_placed_pieces.id'], name=op.f('fk_print_jobs_placed_piece_id_order_placed_pieces'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_print_jobs_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_print_jobs'))
    )
    op.create_index('ix_print_jobs_branch_status', 'print_jobs', ['branch_id', 'status'], unique=False)
    op.create_index(op.f('ix_print_jobs_order_id'), 'print_jobs', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_print_jobs_order_id'), table_name='print_jobs')
    op.drop_index('ix_print_jobs_branch_status', table_name='print_jobs')
    op.drop_table('print_jobs')
    op.drop_index(op.f('ix_preorder_status_history_preorder_id'), table_name='preorder_status_history')
    op.drop_table('preorder_status_history')
    op.drop_index(op.f('ix_preorder_review_links_preorder_id'), table_name='preorder_review_links')
    op.drop_table('preorder_review_links')
    op.drop_index(op.f('ix_order_placed_pieces_order_id'), table_name='order_placed_pieces')
    op.drop_index(op.f('ix_order_placed_pieces_board_id'), table_name='order_placed_pieces')
    op.drop_table('order_placed_pieces')
    op.drop_index('ix_preorders_client_status', table_name='preorders')
    op.drop_index('ix_preorders_branch_status', table_name='preorders')
    op.drop_table('preorders')
    op.drop_index('ix_order_status_history_order_id', table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index('ix_order_pieces_order_id', table_name='order_pieces')
    op.drop_table('order_pieces')
    op.drop_index('ix_order_lines_order_id', table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_index(op.f('ix_order_boards_order_id'), table_name='order_boards')
    op.drop_table('order_boards')
    op.drop_index(op.f('ix_order_attachments_order_id'), table_name='order_attachments')
    op.drop_table('order_attachments')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_order_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_orders_client_id', table_name='orders')
    op.drop_index('ix_orders_branch_status', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_optimization_drafts_branch_id'), table_name='optimization_drafts')
    op.drop_table('optimization_drafts')
    op.drop_index('ix_user_login_events_user_created', table_name='user_login_events')
    op.drop_table('user_login_events')
    op.drop_table('settings')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_products_type'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_print_agents_branch_id'), table_name='print_agents')
    op.drop_table('print_agents')
    op.drop_table('clients')
    op.drop_table('additional_services')
    # Break the users <-> branches cycle: drop the branch_id FK, then branches
    # (which drops its FKs back to users), then users.
    op.drop_constraint(op.f('fk_users_branch_id_branches'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_branches_code'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_branch_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
